<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="homePage.aspx.cs" Inherits="burgerLeaders.homePage"  %>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>
<%@ Register assembly="DevExpress.Web.v20.2, Version=20.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web" tagprefix="dx" %>
<asp:content ID="content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">



  

    &nbsp;<br />
&nbsp;
<table class="dx-justification">
    <tr>
        <td class="auto-style11"><dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" Height="435px" ImageSourceFolder="~/imageSlider" Width="1499px">
    <SettingsNavigationBar Mode="Dots" />
    <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
</dx:ASPxImageSlider>
        </td>
        <td class="auto-style12"></td>
    </tr>
    <tr>
        <td class="auto-style23">
<asp:Image ID="Image1" runat="server" Height="316px" ImageUrl="~/images/c1.jpg" Width="785px" CssClass="auto-style9 auto-style21" />
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td class="auto-style23">
<asp:Label ID="Label1" runat="server" Font-Size="Larger" Text="Get all your BurgerLeader's favorites delivered right to your doorstep with BurgerLeader's Delivery on Uber Eats."></asp:Label>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td class="auto-style23"><asp:Image ID="Image2" runat="server" Height="316px" ImageUrl="~/images/c3.jpg" Width="785px" CssClass="auto-style22" />
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td class="auto-style23"><asp:Label ID="Label2" runat="server" Font-Size="Larger" Text="come by your nearst BurgerLeaders Branch and get Our New Burger!"></asp:Label>
        </td>
        <td>&nbsp;</td>
    </tr>
</table>
&nbsp; 
        
        


</asp:content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="head">
    <style type="text/css">
    .auto-style21 {
        text-align: center;
    }
    .auto-style22 {
        text-align: center;
    }
    .auto-style23 {
        width: 100%;
        height: 33px;
        text-align: center;
    }
</style>
</asp:Content>

